THEME_WELCOME_MESSAGE: "Together we will learn to adapt to climate change!"
THEME_PRIMARY_COLOR: "#4d769c"

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
# THEME_FOOTER_NAV_LINKS:
#   - title: "About"
#     url: "https://www.climateireland.ie/#!/about"
#   - title: "Contact"
#     url: "https://www.climateireland.ie/#!/contact"
# THEME_FOOTER_LEGAL_LINKS:
#     - title: "Terms of service"
#       url: "/tos"
#     - title: "cil_theme_v1"
#       url: "https://github.com/overhangio/indigo"
PLATFORM_NAME: Climate Ireland Learning
